HTTP/1.1 200 OK
Server: nginx/1.4.1 (Ubuntu)
Date: Thu, 27 Feb 2014 00:25:45 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Cache-Control: max-age=0

{
  "objects": [
    {
      "name": "", 
      "url": "/sessions/2014/2/27/65/", 
      "start_time": "2014-02-27T00:08:15+00:00", 
      "volume_ml": 222.0, 
      "is_active": true, 
      "end_time": "2014-02-27T03:08:15+00:00", 
      "id": 65
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/26/64/", 
      "start_time": "2014-02-26T15:19:12+00:00", 
      "volume_ml": 1189.0, 
      "is_active": false, 
      "end_time": "2014-02-26T18:44:53+00:00", 
      "id": 64
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/24/63/", 
      "start_time": "2014-02-24T19:42:54+00:00", 
      "volume_ml": 2206.0, 
      "is_active": false, 
      "end_time": "2014-02-25T01:17:13+00:00", 
      "id": 63
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/23/62/", 
      "start_time": "2014-02-23T15:33:57+00:00", 
      "volume_ml": 1178.0, 
      "is_active": false, 
      "end_time": "2014-02-23T20:37:20+00:00", 
      "id": 62
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/23/61/", 
      "start_time": "2014-02-23T01:15:40+00:00", 
      "volume_ml": 242.0, 
      "is_active": false, 
      "end_time": "2014-02-23T04:15:40+00:00", 
      "id": 61
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/22/60/", 
      "start_time": "2014-02-22T19:30:23+00:00", 
      "volume_ml": 417.0, 
      "is_active": false, 
      "end_time": "2014-02-22T22:31:03+00:00", 
      "id": 60
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/21/59/", 
      "start_time": "2014-02-21T21:07:52+00:00", 
      "volume_ml": 349.0, 
      "is_active": false, 
      "end_time": "2014-02-22T01:11:52+00:00", 
      "id": 59
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/21/58/", 
      "start_time": "2014-02-21T11:41:30+00:00", 
      "volume_ml": 439.0, 
      "is_active": false, 
      "end_time": "2014-02-21T15:39:01+00:00", 
      "id": 58
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/20/57/", 
      "start_time": "2014-02-20T21:24:36+00:00", 
      "volume_ml": 2449.0, 
      "is_active": false, 
      "end_time": "2014-02-21T02:06:29+00:00", 
      "id": 57
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/20/56/", 
      "start_time": "2014-02-20T11:45:45+00:00", 
      "volume_ml": 1156.0, 
      "is_active": false, 
      "end_time": "2014-02-20T17:58:56+00:00", 
      "id": 56
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/20/55/", 
      "start_time": "2014-02-20T06:30:21+00:00", 
      "volume_ml": 354.0, 
      "is_active": false, 
      "end_time": "2014-02-20T09:30:21+00:00", 
      "id": 55
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/19/54/", 
      "start_time": "2014-02-19T06:40:30+00:00", 
      "volume_ml": 10634.0, 
      "is_active": false, 
      "end_time": "2014-02-20T05:08:49+00:00", 
      "id": 54
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/18/53/", 
      "start_time": "2014-02-18T22:53:49+00:00", 
      "volume_ml": 2707.0, 
      "is_active": false, 
      "end_time": "2014-02-19T06:22:15+00:00", 
      "id": 53
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/18/52/", 
      "start_time": "2014-02-18T18:47:48+00:00", 
      "volume_ml": 357.0, 
      "is_active": false, 
      "end_time": "2014-02-18T21:47:48+00:00", 
      "id": 52
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/18/51/", 
      "start_time": "2014-02-18T01:18:39+00:00", 
      "volume_ml": 2144.0, 
      "is_active": false, 
      "end_time": "2014-02-18T04:18:55+00:00", 
      "id": 51
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/17/50/", 
      "start_time": "2014-02-17T16:01:43+00:00", 
      "volume_ml": 419.0, 
      "is_active": false, 
      "end_time": "2014-02-17T19:01:43+00:00", 
      "id": 50
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/16/49/", 
      "start_time": "2014-02-16T20:53:19+00:00", 
      "volume_ml": 1140.0, 
      "is_active": false, 
      "end_time": "2014-02-17T00:50:56+00:00", 
      "id": 49
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/16/48/", 
      "start_time": "2014-02-16T01:03:22+00:00", 
      "volume_ml": 859.0, 
      "is_active": false, 
      "end_time": "2014-02-16T06:36:21+00:00", 
      "id": 48
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/14/47/", 
      "start_time": "2014-02-14T14:41:07+00:00", 
      "volume_ml": 416.0, 
      "is_active": false, 
      "end_time": "2014-02-14T17:41:07+00:00", 
      "id": 47
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/14/46/", 
      "start_time": "2014-02-14T02:22:12+00:00", 
      "volume_ml": 219.0, 
      "is_active": false, 
      "end_time": "2014-02-14T05:22:12+00:00", 
      "id": 46
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/13/45/", 
      "start_time": "2014-02-13T18:27:39+00:00", 
      "volume_ml": 224.0, 
      "is_active": false, 
      "end_time": "2014-02-13T21:27:39+00:00", 
      "id": 45
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/12/44/", 
      "start_time": "2014-02-12T18:32:24+00:00", 
      "volume_ml": 773.0, 
      "is_active": false, 
      "end_time": "2014-02-12T22:18:22+00:00", 
      "id": 44
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/12/43/", 
      "start_time": "2014-02-12T06:14:39+00:00", 
      "volume_ml": 416.0, 
      "is_active": false, 
      "end_time": "2014-02-12T10:26:41+00:00", 
      "id": 43
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/11/42/", 
      "start_time": "2014-02-11T19:45:42+00:00", 
      "volume_ml": 412.0, 
      "is_active": false, 
      "end_time": "2014-02-11T22:45:42+00:00", 
      "id": 42
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/11/41/", 
      "start_time": "2014-02-11T04:55:09+00:00", 
      "volume_ml": 714.0, 
      "is_active": false, 
      "end_time": "2014-02-11T08:10:10+00:00", 
      "id": 41
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/10/40/", 
      "start_time": "2014-02-10T21:21:52+00:00", 
      "volume_ml": 304.0, 
      "is_active": false, 
      "end_time": "2014-02-11T00:21:52+00:00", 
      "id": 40
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/10/39/", 
      "start_time": "2014-02-10T08:39:47+00:00", 
      "volume_ml": 725.0, 
      "is_active": false, 
      "end_time": "2014-02-10T11:40:03+00:00", 
      "id": 39
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/10/38/", 
      "start_time": "2014-02-10T03:36:04+00:00", 
      "volume_ml": 428.0, 
      "is_active": false, 
      "end_time": "2014-02-10T06:36:04+00:00", 
      "id": 38
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/8/37/", 
      "start_time": "2014-02-08T22:54:31+00:00", 
      "volume_ml": 2441.0, 
      "is_active": false, 
      "end_time": "2014-02-09T01:55:18+00:00", 
      "id": 37
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/8/36/", 
      "start_time": "2014-02-08T18:21:44+00:00", 
      "volume_ml": 123.0, 
      "is_active": false, 
      "end_time": "2014-02-08T21:21:44+00:00", 
      "id": 36
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/7/35/", 
      "start_time": "2014-02-07T17:33:01+00:00", 
      "volume_ml": 133.0, 
      "is_active": false, 
      "end_time": "2014-02-07T20:33:01+00:00", 
      "id": 35
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/7/34/", 
      "start_time": "2014-02-07T14:16:58+00:00", 
      "volume_ml": 440.0, 
      "is_active": false, 
      "end_time": "2014-02-07T17:16:58+00:00", 
      "id": 34
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/6/33/", 
      "start_time": "2014-02-06T19:34:05+00:00", 
      "volume_ml": 4672.0, 
      "is_active": false, 
      "end_time": "2014-02-07T11:03:03+00:00", 
      "id": 33
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/6/32/", 
      "start_time": "2014-02-06T06:39:41+00:00", 
      "volume_ml": 390.0, 
      "is_active": false, 
      "end_time": "2014-02-06T09:39:41+00:00", 
      "id": 32
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/5/31/", 
      "start_time": "2014-02-05T15:41:57+00:00", 
      "volume_ml": 7322.0, 
      "is_active": false, 
      "end_time": "2014-02-06T06:05:44+00:00", 
      "id": 31
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/5/30/", 
      "start_time": "2014-02-05T04:29:23+00:00", 
      "volume_ml": 238.0, 
      "is_active": false, 
      "end_time": "2014-02-05T07:29:23+00:00", 
      "id": 30
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/4/29/", 
      "start_time": "2014-02-04T18:43:07+00:00", 
      "volume_ml": 3188.0, 
      "is_active": false, 
      "end_time": "2014-02-05T01:41:45+00:00", 
      "id": 29
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/4/28/", 
      "start_time": "2014-02-04T05:01:04+00:00", 
      "volume_ml": 404.0, 
      "is_active": false, 
      "end_time": "2014-02-04T08:01:04+00:00", 
      "id": 28
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/3/27/", 
      "start_time": "2014-02-03T20:45:12+00:00", 
      "volume_ml": 441.0, 
      "is_active": false, 
      "end_time": "2014-02-03T23:45:12+00:00", 
      "id": 27
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/1/26/", 
      "start_time": "2014-02-01T11:20:16+00:00", 
      "volume_ml": 167.0, 
      "is_active": false, 
      "end_time": "2014-02-01T14:20:16+00:00", 
      "id": 26
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/2/1/25/", 
      "start_time": "2014-02-01T06:06:02+00:00", 
      "volume_ml": 371.0, 
      "is_active": false, 
      "end_time": "2014-02-01T09:06:02+00:00", 
      "id": 25
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/31/24/", 
      "start_time": "2014-01-31T23:38:11+00:00", 
      "volume_ml": 767.0, 
      "is_active": false, 
      "end_time": "2014-02-01T02:40:36+00:00", 
      "id": 24
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/29/23/", 
      "start_time": "2014-01-29T18:43:00+00:00", 
      "volume_ml": 20085.0, 
      "is_active": false, 
      "end_time": "2014-01-30T03:35:00+00:00", 
      "id": 23
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/28/22/", 
      "start_time": "2014-01-28T19:22:00+00:00", 
      "volume_ml": 7361.0, 
      "is_active": false, 
      "end_time": "2014-01-29T00:51:00+00:00", 
      "id": 22
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/27/21/", 
      "start_time": "2014-01-27T20:40:00+00:00", 
      "volume_ml": 544.0, 
      "is_active": false, 
      "end_time": "2014-01-28T00:11:00+00:00", 
      "id": 21
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/25/20/", 
      "start_time": "2014-01-25T18:52:00+00:00", 
      "volume_ml": 5848.0, 
      "is_active": false, 
      "end_time": "2014-01-26T00:15:00+00:00", 
      "id": 20
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/23/19/", 
      "start_time": "2014-01-23T22:02:00+00:00", 
      "volume_ml": 4997.0, 
      "is_active": false, 
      "end_time": "2014-01-24T02:45:00+00:00", 
      "id": 19
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/21/18/", 
      "start_time": "2014-01-21T18:06:00+00:00", 
      "volume_ml": 9777.0, 
      "is_active": false, 
      "end_time": "2014-01-22T02:52:00+00:00", 
      "id": 18
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/20/17/", 
      "start_time": "2014-01-20T21:50:00+00:00", 
      "volume_ml": 4317.0, 
      "is_active": false, 
      "end_time": "2014-01-21T02:15:00+00:00", 
      "id": 17
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/17/16/", 
      "start_time": "2014-01-17T20:42:00+00:00", 
      "volume_ml": 2342.0, 
      "is_active": false, 
      "end_time": "2014-01-18T00:59:00+00:00", 
      "id": 16
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/16/15/", 
      "start_time": "2014-01-16T21:36:00+00:00", 
      "volume_ml": 9329.0, 
      "is_active": false, 
      "end_time": "2014-01-17T04:12:00+00:00", 
      "id": 15
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/13/14/", 
      "start_time": "2014-01-13T21:45:00+00:00", 
      "volume_ml": 4290.0, 
      "is_active": false, 
      "end_time": "2014-01-14T02:55:00+00:00", 
      "id": 14
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/12/13/", 
      "start_time": "2014-01-12T18:23:00+00:00", 
      "volume_ml": 4365.0, 
      "is_active": false, 
      "end_time": "2014-01-12T23:59:00+00:00", 
      "id": 13
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/10/12/", 
      "start_time": "2014-01-10T20:42:00+00:00", 
      "volume_ml": 2121.0, 
      "is_active": false, 
      "end_time": "2014-01-11T00:33:00+00:00", 
      "id": 12
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/7/11/", 
      "start_time": "2014-01-07T20:30:00+00:00", 
      "volume_ml": 4226.0, 
      "is_active": false, 
      "end_time": "2014-01-08T00:51:00+00:00", 
      "id": 11
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/6/10/", 
      "start_time": "2014-01-06T18:36:00+00:00", 
      "volume_ml": 4863.0, 
      "is_active": false, 
      "end_time": "2014-01-07T00:16:00+00:00", 
      "id": 10
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/4/9/", 
      "start_time": "2014-01-04T20:02:00+00:00", 
      "volume_ml": 1197.0, 
      "is_active": false, 
      "end_time": "2014-01-05T00:22:00+00:00", 
      "id": 9
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/3/8/", 
      "start_time": "2014-01-03T19:34:00+00:00", 
      "volume_ml": 6136.0, 
      "is_active": false, 
      "end_time": "2014-01-04T01:12:00+00:00", 
      "id": 8
    }, 
    {
      "name": "", 
      "url": "/sessions/2014/1/1/7/", 
      "start_time": "2014-01-01T18:21:00+00:00", 
      "volume_ml": 4509.0, 
      "is_active": false, 
      "end_time": "2014-01-01T23:50:00+00:00", 
      "id": 7
    }, 
    {
      "name": "", 
      "url": "/sessions/2013/12/30/6/", 
      "start_time": "2013-12-30T20:53:00+00:00", 
      "volume_ml": 5500.0, 
      "is_active": false, 
      "end_time": "2013-12-31T01:50:00+00:00", 
      "id": 6
    }, 
    {
      "name": "", 
      "url": "/sessions/2013/12/27/5/", 
      "start_time": "2013-12-27T21:12:00+00:00", 
      "volume_ml": 9285.0, 
      "is_active": false, 
      "end_time": "2013-12-28T02:58:00+00:00", 
      "id": 5
    }, 
    {
      "name": "", 
      "url": "/sessions/2013/12/26/4/", 
      "start_time": "2013-12-26T18:13:00+00:00", 
      "volume_ml": 12956.0, 
      "is_active": false, 
      "end_time": "2013-12-27T01:11:00+00:00", 
      "id": 4
    }, 
    {
      "name": "", 
      "url": "/sessions/2013/12/23/3/", 
      "start_time": "2013-12-23T18:11:00+00:00", 
      "volume_ml": 10139.0, 
      "is_active": false, 
      "end_time": "2013-12-24T02:32:00+00:00", 
      "id": 3
    }, 
    {
      "name": "", 
      "url": "/sessions/2013/12/21/2/", 
      "start_time": "2013-12-21T20:50:00+00:00", 
      "volume_ml": 2488.0, 
      "is_active": false, 
      "end_time": "2013-12-22T01:17:00+00:00", 
      "id": 2
    }, 
    {
      "name": "", 
      "url": "/sessions/2013/12/18/1/", 
      "start_time": "2013-12-18T20:10:00+00:00", 
      "volume_ml": 774.0, 
      "is_active": false, 
      "end_time": "2013-12-18T23:49:00+00:00", 
      "id": 1
    }
  ], 
  "meta": {
    "result": "ok"
  }
}