HTTP/1.1 200 OK
Server: nginx/1.4.1 (Ubuntu)
Date: Thu, 27 Feb 2014 00:45:51 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Cache-Control: max-age=0

{
  "object": {
    "name": "", 
    "url": "/sessions/2014/2/27/65/", 
    "start_time": "2014-02-27T00:08:15+00:00", 
    "volume_ml": 222.0, 
    "is_active": true, 
    "end_time": "2014-02-27T03:08:15+00:00", 
    "id": 65
  }, 
  "meta": {
    "result": "ok"
  }
}